//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace Ed_LearnPad_LoginWS.ER_Login {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LogMeSecureSoap", Namespace="https://my.edresources.com/service/")]
    public partial class LogMeSecure : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SecUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SecUserLogOutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LogMeSecure() {
            this.Url = global::Ed_LearnPad_LoginWS.Properties.Settings.Default.Ed_LearnPad_LoginWS_ER_Login_LogMeSecure;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SecUserInfoCompletedEventHandler SecUserInfoCompleted;
        
        /// <remarks/>
        public event SecUserLogOutCompletedEventHandler SecUserLogOutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://my.edresources.com/service/SecUserInfo", RequestNamespace="https://my.edresources.com/service/", ResponseNamespace="https://my.edresources.com/service/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SecUserInfo(string Username, string Password, string Token) {
            object[] results = this.Invoke("SecUserInfo", new object[] {
                        Username,
                        Password,
                        Token});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SecUserInfoAsync(string Username, string Password, string Token) {
            this.SecUserInfoAsync(Username, Password, Token, null);
        }
        
        /// <remarks/>
        public void SecUserInfoAsync(string Username, string Password, string Token, object userState) {
            if ((this.SecUserInfoOperationCompleted == null)) {
                this.SecUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSecUserInfoOperationCompleted);
            }
            this.InvokeAsync("SecUserInfo", new object[] {
                        Username,
                        Password,
                        Token}, this.SecUserInfoOperationCompleted, userState);
        }
        
        private void OnSecUserInfoOperationCompleted(object arg) {
            if ((this.SecUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SecUserInfoCompleted(this, new SecUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://my.edresources.com/service/SecUserLogOut", RequestNamespace="https://my.edresources.com/service/", ResponseNamespace="https://my.edresources.com/service/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SecUserLogOut(int LoginID, string LoginGUID, string Token) {
            object[] results = this.Invoke("SecUserLogOut", new object[] {
                        LoginID,
                        LoginGUID,
                        Token});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SecUserLogOutAsync(int LoginID, string LoginGUID, string Token) {
            this.SecUserLogOutAsync(LoginID, LoginGUID, Token, null);
        }
        
        /// <remarks/>
        public void SecUserLogOutAsync(int LoginID, string LoginGUID, string Token, object userState) {
            if ((this.SecUserLogOutOperationCompleted == null)) {
                this.SecUserLogOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSecUserLogOutOperationCompleted);
            }
            this.InvokeAsync("SecUserLogOut", new object[] {
                        LoginID,
                        LoginGUID,
                        Token}, this.SecUserLogOutOperationCompleted, userState);
        }
        
        private void OnSecUserLogOutOperationCompleted(object arg) {
            if ((this.SecUserLogOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SecUserLogOutCompleted(this, new SecUserLogOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SecUserInfoCompletedEventHandler(object sender, SecUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SecUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SecUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SecUserLogOutCompletedEventHandler(object sender, SecUserLogOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SecUserLogOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SecUserLogOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591